server:
  port: 8601

spring:
  application:
    name: DISTANCE_SERVER
  cloud:
    #
    # nacos配置
    #
    nacos:
      discovery:
        server-addr: 192.168.101.7:8848
  servlet:
    #
    # 文件上传大小配置
    #
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#
# 文件存储 SDK 配置
#
sdk:
  qiniu:
    access: tchS3evhxj_qcf_x9JIJlZDD7Xv83fNTMuARj8Xp
    secret: hB22f61gS6art-d2XDxvCl-ka3gcovxfuaKncbBp
    bucket: store-distance-avatar