spring:
  profiles:
    active: dev
  application:
    name: DISTANCE
  cloud:
    nacos:
      #
      # 配置中心
      #
      config:
        enabled: true
        server-addr: 123.60.211.203:8848
        namespace: dev
        group: DISTANCE_GROUP
  config:
    import:
      - optional:nacos:application-dev.yml