server:
  port: 8080

spring:
  application:
    name: DISTANCE_SERVER
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.101.7:8848

sdk:
  qiniu:
    access: tchS3evhxj_qcf_x9JIJlZDD7Xv83fNTMuARj8Xp
    secret: hB22f61gS6art-d2XDxvCl-ka3gcovxfuaKncbBp
    bucket: store-distance-avatar