spring:
  profiles:
    active: dev
  application:
    name: DISTANCE-SRV
#  cloud:
#    nacos:
#      #
#      # 配置中心
#      #
#      config:
#        enabled: true
#        server-addr: 123.60.211.203:8848
#        namespace: ${spring.profiles.active}
#        group: DISTANCE_GROUP
#  config:
#    import:
#      - optional:nacos:distance-application.yml