server:
  port: 8602

spring:
  application:
    name: DISTANCE
  cloud:
    #
    # nacos配置
    #
    nacos:
      discovery:
        server-addr: 123.60.211.203:8848
        username: nacos
        password: nacos
        namespace: dev
  servlet:
    #
    # 文件上传大小配置
    #
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    #
    # druid 数据源配置
    #
    druid:
      url: jdbc:mysql://123.60.211.203:3306/distance?useSSL=false&serverTimezone=UTC
      username: root
      password: root
      initial-size: 5
      max-active: 20
      max-wait: 3000
      validation-query: select 1
      driver-class-name: com.mysql.cj.jdbc.Driver
  #
  # redis配置
  #
  redis:
    host: 123.60.211.203
    port: 6379
    timeout: 3000

#
# 文件存储 SDK 配置
#
sdk:
  qiniu:
    access: tchS3evhxj_qcf_x9JIJlZDD7Xv83fNTMuARj8Xp
    secret: hB22f61gS6art-d2XDxvCl-ka3gcovxfuaKncbBp
    bucket: store-distance-avatar